### ISSUE TITLE
move to rpm-software-management org

### ISSUE THREAD

**Issue by dustymabe** [cgwalters/micro-yuminst#6]
@cgwalters @ignatenkobrain @jsilhan can we get the code from [the fork](https://github.com/ignatenkobrain/microdnf) merged and then move this repo under the rpm-software-management org ? I assume that is where we want it to live.

**Comment by jsilhan** [comment]
we moved Igor's repo into https://github.com/rpm-software-management/microdnf . Igor rewritten it from scratch for some reason, so it has different history.

@cgwalters can this repo be redirected to https://github.com/rpm-software-management/microdnf somehow? Does github support that?

We should then extend README in https://github.com/rpm-software-management/microdnf that Microdnf was based on micro-yuminst.

**Comment by cgwalters** [comment]
I don't think we can directly redirect, but we can do: https://github.com/cgwalters/micro-yuminst/commit/5f6028d4f8fee7e15db9d29a6c976c3c39d719b4
